services:
  django:
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/django:/app
      - ${LOG_VOLUME}:/app/logs
    ports:
      - "8000:8000"
  mt5:
    ports:
      - "5678:5678"